### ISSUE TITLE
error after new Tradfri version upgrades

### ISSUE THREAD

**Issue by Peekewee** [szokeptr/homebridge-tradfri-plugin#18]
Yesterday I received an version upgrade of the remote control and lamps. Now the plugin doesn't work any more. I receive the following message:
[8/10/2017, 5:12:25 PM] Loading 1 platforms...
[8/10/2017, 5:12:25 PM] [Tradfri] Initializing IkeaTradfri platform...
[8/10/2017, 5:12:27 PM] [Tradfri] Initializing platform accessory 'TRADFRI bulb E14 WS opal 400lm - 65537'...
[8/10/2017, 5:12:27 PM] [Tradfri] Initializing platform accessory 'TRADFRI bulb E27 WS opal 980lm 2 - 65538'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at Server._listen2 (net.js:1276:14)
    at listen (net.js:1312:10)
    at Server.listen (net.js:1403:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:486:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)

**Comment by szokeptr** [comment]
Homebridge’s port (51826) is in use by other an process. Perhaps another instance of homebridge running?

**Comment by Peekewee** [comment]
Hi, yes this was the case. Now homebridge loads correctly but the homebridge is not showing up anymore in the Home app on my iPhone.

**Comment by toshibochan** [comment]
Ikea server update and now work with HomeKit! Don't need homebridge anymore

**Comment by toshibochan** [comment]
https://www.google.com/amp/s/www.engadget.com/amp/2017/08/10/ikea-tradfri-apple-homekit-integration/

**Comment by Peekewee** [comment]
Update of the server is not yet functional. Ikea SE posted the following message on their facebook page yesterday:

There has been information going out today about the compatibility of TRÅDFRI. We can now inform you that TRÅDFRI is not yet compatible with Apple, Amazon and Google. The plan is that everything will work as we’d like this fall.

We are very sorry for the confusion!

**Comment by szokeptr** [comment]
In theory the gateway now supports HomeKit natively, however I still updated the plugin to handle the new DTLS sessions.
