### ISSUE TITLE
Unhandled Error on launch

### ISSUE THREAD

**Issue by Gernot** [szokeptr/homebridge-tradfri-plugin#22]
Sorry if it's a beginners mistake: I have no idea about node.js and where to look, as the error message is too generic for me to know where to begin.

I installed a fresh new Raspberry Pi, Homebridge runs Logitech Harmony stuff, so that's set up correctly. I installed `coap-client` and added the Trådfri plugin into `config.json`:

```
		{
  			"platform": "IkeaTradfri",
 			"name": "Tradfri",
			"host": "[redacted]",
  			"key": "[redacted]"
		}
```

Here's the complete output when I start Homebridge:

```
[9/26/2017, 4:30:22 PM] Loaded plugin: homebridge-harmonyhub
[9/26/2017, 4:30:23 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[9/26/2017, 4:30:23 PM] ---
[9/26/2017, 4:30:23 PM] Loaded plugin: homebridge-tradfri-plugin
[9/26/2017, 4:30:23 PM] Registering platform 'homebridge-tradfri.IkeaTradfri'
[9/26/2017, 4:30:23 PM] ---
[9/26/2017, 4:30:23 PM] Loaded config.json with 0 accessories and 2 platforms.
[9/26/2017, 4:30:23 PM] ---
[9/26/2017, 4:30:23 PM] Loading 2 platforms...
[9/26/2017, 4:30:23 PM] [Harmony Hub] Initializing HarmonyHub platform...
[9/26/2017, 4:30:23 PM] [Tradfri] Initializing IkeaTradfri platform...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::61991
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at ResponseCollector.start (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/responseCollector.js:33:6)
    at Explorer.start (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/explorer.js:74:26)
    at new HomePlatform (/usr/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:66:17)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

Thanks for your help (submitted this as an issue, because whatever it is, there should be an error message instead of an unhandled exception, right?)

**Comment by Gernot** [comment]
Seems like a reboot fixed it. Ignore this if you want ;-)

**Comment by szokeptr** [comment]
Another instance of Homebridge is already running.
