### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by soulsf** [szokeptr/homebridge-tradfri-plugin#31]
I get this error:

(node:23961) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token d in JSON at position 0
    at JSON.parse (<anonymous>)
    at exec (/opt/nodejs/lib/node_modules/homebridge-tradfri-plugin/index.js:93:43)
    at ChildProcess.exithandler (child_process.js:268:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:23961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

---

node v8.12.0
npm 6.4.1

fresh install. Changed "Client_identity" to another value, since my username on the ikea gateway is different. coap-client request works:

# coap-client -m get -u "raspberry" -k "XXXX" "coaps://XXXXX:5684/15011/15012"
v:1 t:CON c:GET i:9e97 {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 432 bytes cleartext
{"9080":60,"9023":"3.tradfri.pool.ntp.org","9069":1556915553,"9059":1556922583,"9093":0,"9060":"2019-05-03T22:29:43.014568Z","9061":0,"9062":0,"9075":33,"9029":"1.8.25","9081":"7e172d5204400053","9082":true,"9078":1,"9077":27,"9083":"330-42-015","9054":0,"9076":10,"9055":0,"9066":5,"9103":"","9071":0,"9200":"5a444722-739d-4173-b379-99157963209a","9072":5,"9073":2,"9074":20,"9107":1,"9079":0,"9092":0,"9106":0,"9105":0}

**Comment by soulsf** [comment]
OK, my bridge was somehow fucked up. Fixed it - sorry.
